#  6. Example of docker-compose yaml - Using Named Volumes

##################   START #########################

version: "3.8"
services:
  learn-ports-service:
    image: nginx
    ports:
      - "8080:80"
    environment:
      CITY: "$Location"
      TOPIC: "Docker and Docker Compose"
    depends_on: 
      - training-service 
  interview-service:
    image: redis
    environment: 
      CITY: "Princeton"
      STATE: "New Jersey "
    volumes: 
      -  devops-interview-vol:/usr/test-data
  training-service:
    image: nginx
    ports:
      - "9000:80"
    environment: 
      CITY: "PONNUR"
      STATE: "Andhra Pradesh "
volumes: 
  devops-interview-vol:
 
##################   END   #########################
