#  5.Example of docker-compose yaml - To build image using Dockerfile from git

##################   START #########################

version: "3.8"
services:
  learn-ports-service:
    image: nginx
    ports:
      - "8080:80"
    depends_on: 
      - training-service 
  training-service:
    image: nginx
    ports:
      - "9000:80"
    environment: 
      CITY: "BANGALORE"
      STATE: "KARNATAKA "
  how-2-build-service:
    ##build: "./"
    build:
      context: https://github.com/mogalipuvvu/docker-demo.git#main:4-WORKDIR-example
      ##dockerfile: 4-WORKDIR-example/Dockerfile
    image: test-image-build-at-runtime 
    environment: 
      country: "India"  
##################   END   #########################

#  Refer the docker documentation of build - https://docs.docker.com/engine/reference/commandline/build/#git-repositories
